---
title: "photosearcher"
author: "Nathan Fox"
date: "19-29-04"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{photosearcher}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette provides an overview of the R package `photosearcher`.

###Search for photographs and their metadata
```{r}
  #Search for all images tagged trains on the 1st of January 2019
  library(photosearcher)


  trains <- photo_search(mindate = "2019-01-01", maxdate = "2019-01-01", text = "train", api_key = "3863b3b3d95341cff763f05e989012b7")
  
  #Display first few returned variables for first image
  trains[1, 1:7]
```

###Get a flickr users data
```{r}
  #Find a users hometown
  user <- user_info(user_id = "22299651@N07", api_key = "3863b3b3d95341cff763f05e989012b7")
  
  user$hometown
 
```

###Get the top tags for location
```{r}
  #Find the tags for Southampton, UK
  location <- location_tags(woe_id = 35356, api_key =    "3863b3b3d95341cff763f05e989012b7")

  head(location)

```

###Get terms related to another tag
```{r}
  #Find tags most associated with the word church
  church <- related_terms(term = "church", api_key =  "3863b3b3d95341cff763f05e989012b7")
  
  head(church)

```

###Download an image
```{r eval=FALSE}
  #Download an image
  download_images(photo_id = "47416147181")

```

